package model;

public enum ErrorCode {
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    INTERNAL_SERVER_ERROR,
    DATABASE_ERROR,
    INVALID_CREDENTIALS,
    USER_NOT_FOUND,
    GAME_NOT_FOUND
}
